### ISSUE TITLE
Problem to show product images

### ISSUE THREAD

**Issue by al3ssandr000** [organicinternet/magento-configurable-simple#103]
Hi,
i've installed SCP on Magento 1.7.0.2 and set configuration from System-> Configuration-> SCP config
Now, when i'm watching to my default configurable product in frontend and try to select Colour and Size, nothing appears and in Firebug i can see this error:
"TypeError: $(imageEl) is null

this.containerEl = $(imageEl).parentNode;"

At the end of the page I can clearly see this lines, i think from somewhere in the code:

/product
/gallery
/id/5/image/2/

Anyone can help me?

Thank you.

**Comment by szokart** [comment]
Probably use another photo gallery from the default

change:
in app\code\community\OrganicInternet\SimpleConfigurableProducts\Catalog\Block\Product\View\Type\Configurable.php

change:( row:89)
$config["imageZoomer"] = $childBlock->setTemplate('catalog/product/view/media.phtml')

replace with
$config["imageZoomer"] = $childBlock->setTemplate('YOUR BLOCK MEDIA')
