### ISSUE TITLE
Full crash: Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media::renderCloudOptions

### ISSUE THREAD

**Issue by kshnurov** [organicinternet/magento-configurable-simple#12]
Just installed SCP, Magento 1.4.1.1. When trying to open configurable product page, get this:

a:5:{i:0;s:122:"Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media::renderCloudOptions(Array
(
)
)";i:1;s:4160:"#0 /home/zx0/www/shop_megabochkaru/app/design/frontend/default/default/template/moo/catalog/product/view/media.phtml(34): Varien_Object->__call('renderCloudOpti...', Array)
#1 /home/zx0/www/shop_megabochkaru/app/design/frontend/default/default/template/moo/catalog/product/view/media.phtml(34): OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media->renderCloudOptions()
#2 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(212): include('/home/zx0/www/s...')
#3 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(239): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#4 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(253): Mage_Core_Block_Template->renderView()
#5 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(753): Mage_Core_Block_Template->_toHtml()
#6 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(520): Mage_Core_Block_Abstract->toHtml()
#7 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(471): Mage_Core_Block_Abstract->_getChildHtml('media', true)
#8 /home/zx0/www/shop_megabochkaru/app/design/frontend/base/default/template/catalog/product/view.phtml(96): Mage_Core_Block_Abstract->getChildHtml('media')
#9 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(212): include('/home/zx0/www/s...')
#10 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(239): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#11 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(253): Mage_Core_Block_Template->renderView()
#12 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(753): Mage_Core_Block_Template->_toHtml()
#13 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#14 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(753): Mage_Core_Block_Text_List->_toHtml()
#15 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(520): Mage_Core_Block_Abstract->toHtml()
#16 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(471): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#17 /home/zx0/www/shop_megabochkaru/app/design/frontend/base/default/template/page/2columns-right.phtml(48): Mage_Core_Block_Abstract->getChildHtml('content')
#18 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(212): include('/home/zx0/www/s...')
#19 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(239): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#20 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Template.php(253): Mage_Core_Block_Template->renderView()
#21 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Block/Abstract.php(753): Mage_Core_Block_Template->_toHtml()
#22 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Model/Layout.php(529): Mage_Core_Block_Abstract->toHtml()
#23 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Controller/Varien/Action.php(389): Mage_Core_Model_Layout->getOutput()
#24 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Catalog/controllers/ProductController.php(153): Mage_Core_Controller_Varien_Action->renderLayout()
#25 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_ProductController->viewAction()
#26 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#27 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Controller/Varien/Front.php(177): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#28 /home/zx0/www/shop_megabochkaru/app/code/core/Mage/Core/Model/App.php(304): Mage_Core_Controller_Varien_Front->dispatch()
#29 /home/zx0/www/shop_megabochkaru/app/Mage.php(596): Mage_Core_Model_App->run(Array)
#30 /home/zx0/www/shop_megabochkaru/index.php(80): Mage::run('', 'store')
#31 {main}";s:3:"url";s:6:"/sauna";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

**Comment by kshnurov** [comment]
Figured out that this was only with old products, created before installing SCP.

**Comment by toasty** [comment]
Hiya - renderCloudOptions isn't part of SCP, nor part of core Magento as far as I know, so I suspect what's happened is that you have another extension installed that has 'rewritten' Catalog_Block_Product_View_Media so that it's own version of the block is used. 

Once you've installed SCP, SCP has rewritten the same class and taken precedence, but the SCP one doesn't have the renderCloudOptions method in it, hence the error. (it's some part of the other extension you have looking for some of it's own code but finding SCP's code instead)

Sometimes running multiple extensions can cause clashes like this.

Your best bet is to do something like copy the SCP methods in Catalog_Block_Product_View_Media into the file from whichever extension adds the renderCloudOptions function, or copy the renderCloudsFunction into SCP's OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media file

Or something equally awkward if you're not a programmer :}

**Comment by kshnurov** [comment]
Yes, the module Moo_CloudZoom extends the same class Catalog_Block_Product_View_Media. Looks like it a magento's architecture bug, the only way is to modify one of the modules :(

**Comment by kshnurov** [comment]
Here is a simple&stupid workaround to make Moo_CloudZoom and SCP work together:

```
 /app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Block/Product/View/Media.php
 @@ -3,7 +3,7 @@
  #SCP: Passed parent productid (which is set by the SCP ajax controller) as the SCP ajax controller needs it again
  #to be able to verify that this simple product belongs to a configurable product that's visible

 -class OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media extends Mage_Catalog_Block_Product_View_Media {
 +class OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media extends Moo_Catalog_Block_Product_View_Media {

      public function getGalleryUrl($image=null)
      {
```

**Comment by toasty** [comment]
I think it's pretty much the best way to do it. 

You probably want to remove the <rewrite>'s from the Moo module's config file too. I'm not quite sure how Magento chooses which extension 'wins' for these things, but it's probably best that only one of them is configured to rewrite the same class.

**Comment by kshnurov** [comment]
Moo extends Mage core module, so it ok - SCP extends Moo which extends Mage.
Very, very bad solution, but it's the quickest way. Other way is to copy SCP code to Moo_CloudZoom, but cloudzoom updates oftenly.
Only hope it will always know where to load Moo_Catalog_Block_Product_View_Media.
Thanks for help!

**Comment by grosykevin** [comment]
Hello, I am having the same problem but I can't solve this problem despite what explain you what is to be done exactly?

a:5:{i:0;s:122:"Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media::renderCloudOptions(Array
(
)
)";i:1;s:4329:"#0 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/moo/catalog/product/view/media.phtml(81): Varien_Object->__call('renderCloudOpti...', Array)
#1 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/moo/catalog/product/view/media.phtml(81): OrganicInternet_SimpleConfigurableProducts_Catalog_Block_Product_View_Media->renderCloudOptions()
#2 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hairqualk...')
#3 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/neosho...')
#4 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#5 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#6 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#7 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('media', true)
#8 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/catalog/product/view.phtml(69): Mage_Core_Block_Abstract->getChildHtml('media')
#9 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hairqualk...')
#10 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/neosho...')
#11 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#12 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#13 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#14 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#15 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#16 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#17 /home/hairqualkn/www/app/design/frontend/neoshop/default/template/page/2columns-right.phtml(57): Mage_Core_Block_Abstract->getChildHtml('content')
#18 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(241): include('/home/hairqualk...')
#19 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/neosho...')
#20 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#21 /home/hairqualkn/www/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#22 /home/hairqualkn/www/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#23 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#24 /home/hairqualkn/www/app/code/core/Mage/Cms/Helper/Page.php(137): Mage_Core_Controller_Varien_Action->renderLayout()
#25 /home/hairqualkn/www/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'no-route')
#26 /home/hairqualkn/www/app/code/core/Mage/Cms/controllers/IndexController.php(75): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'no-route')
#27 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->noRouteAction()
#28 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('noRoute')
#29 /home/hairqualkn/www/app/code/community/ArtsOnIT/OfflineMaintenance/Controller/Router/Standard.php(46): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#30 /home/hairqualkn/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): ArtsOnIT_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#31 /home/hairqualkn/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#32 /home/hairqualkn/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#33 /home/hairqualkn/www/index.php(87): Mage::run('', 'store')
#34 {main}";s:3:"url";s:28:"/body-wave-bresilien-6a.html";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"fr";}
