### ISSUE TITLE
1.7.0.2 CE - There was a problem with reindexing process.

### ISSUE THREAD

**Issue by adamnel** [organicinternet/magento-configurable-simple#134]
Installed directly from Magento Connect. Per the instructions on github, I refreshed the cache and attempted to reindex as well, but get the error "There was a problem with reindexing process." each time I try to reindex prices.

I also get a 404 when attempting to visit the configuration page.

**Comment by adamnel** [comment]
The fix is already present in the git repo, but not via Magento Connect. I downloaded and manually installed the extension and this fixed the problem, but I believe that you could also make the changes necessary from a Magento Connect version of the extension based on what's shown in this patch:

https://github.com/organicinternet/magento-configurable-simple/pull/85/files

**Comment by jenniigalaxy** [comment]
Fix does not work for me on 1.7.0.2 CE.
