### ISSUE TITLE
Pricing not updating dynamically?

### ISSUE THREAD

**Issue by vincepettit** [organicinternet/magento-configurable-simple#14]
We have SCP installed and the pricing is not dynamically updating. If you submit the product with the options selected the correct price shows on the cart, just not on the product, it show's the prices from price instead.

**Comment by toasty** [comment]
Often this is Magento's javascript breaking when you've removed one of the price blocks that it expects to find, but it's hard to say without more info. If it's still a problem you can email/pm me a link and i'll take a quick look.

**Comment by toasty** [comment]
To summarise this one for future reference:

Magento’s Product.js javascript can break if you’ve removed the main price block on the product page. 

Usually there are 2 price blocks on the product page, one that's up near the product name/stock/etc, and another that's nearer the quantity and add to cart button. The Magento js expects to find the one near the product name. If you've removed it, the js will break, causing SCP's javascript to break too, which usually has the result of changing the displayed product price to £0.00.

Specifically, the second of these blocks is a span with id something like ‘product-price-7564_clone’ (the id changes with the product) and the former is similar but without the '_clone', i.e. 'product-price-7564'. It's the former than needs to exist for the js to work.

So either reinstate the other price block, or rename the second one to remove the ‘ _clone’ bit and the Magento js will update the prices.  

If you don't want to reinstate the main price block, to remove the _clone part of the id on the second price block you can change:

```
<?php echo $this->getPriceHtml($_product, false, '_clone') ?>
```

to
    <?php echo $this->getPriceHtml($_product, false)  ?>

in
app/design/frontend/base/default/template/catalog/product/view/price_clone.phtml
