### ISSUE TITLE
Does not work in Fancybox

### ISSUE THREAD

**Issue by tigerofasia** [organicinternet/magento-configurable-simple#150]
I created a quickview on the website I'm working. It's using Fancybox AJAX. When I open up the quickview and select any options, the price won't change but it's working fine if I view the product on the product page and select any options there.

If anyone has encountered this issue, please share. Thank you.

**Comment by sean1982** [comment]
did you manage to fix this problem at all cheers

**Comment by tigerofasia** [comment]
@sean1982 Yup. I just forgot to put an ID to the span element inside the div with a class 'price-box'

**Comment by sean1982** [comment]
@tigerofasia Many thanks for taking the time to reply unfortunatly for me this doesnt fix my issue but thanks anyway
