### ISSUE TITLE
simple product in cart

### ISSUE THREAD

**Issue by ghost** [organicinternet/magento-configurable-simple#179]
Can the extension be extended in such a way that a chosen child product from a configurable product would end up in the shopping cart as a simple product? As if the simple product was added to the cart via its own simple product page

**Comment by fvangils** [comment]
I believe this is covered standard in the module, and can be configured. In our webshop we always add the child product to the cart.

**Comment by ghost** [comment]
You are right, I made a mistake during testing. It works a you describe.
