### ISSUE TITLE
HIghest Price show in Tier Price

### ISSUE THREAD

**Issue by seemaa** [organicinternet/magento-configurable-simple#19]
I want to show highest price in the tier price . where I change to show the highest price only .

**Comment by toasty** [comment]
Hello - I'm not sure that's a bug or issue, more of a question, so might have been better suited to the extension's forums on magentocommerce,com, but anyway...

When you say "highest price in the tier price", what do you mean exactly?

Do you mean: 
1) When tier prices are displayed, only show the most expensive tier price (I don't really understand why you'd want to do this?)
2) When SCP shows a 'price from' price, you want this price to include tier prices, but only the highest one?
3) Something else?

**Comment by toasty** [comment]
closing as old
