### ISSUE TITLE
Is that project dead?

### ISSUE THREAD

**Issue by SchumacherFM** [organicinternet/magento-configurable-simple#190]
- Last commit: a year ago
- Unmerged PRs
- 148 open issues and counting

If so which Fork is the official Fork to contribute to?

I suggest: https://github.com/aligent/magento-configurable-simple

To move on: Close here your issues and PRs and move them to the aligent Repo

Any other suggestions?

**Comment by barryvdh** [comment]
This pulls a lot: https://github.com/organicinternet/magento-configurable-simple/pull/195
So maybe https://github.com/obigroup/magento-configurable-simple ?

I'm not sure, but want to know also..

**Comment by SchumacherFM** [comment]
Yes!
