### ISSUE TITLE
Ajax call to update the price does not work in a clustered environment

### ISSUE THREAD

**Issue by dphilbrook** [organicinternet/magento-configurable-simple#2]
In a clustered environment the SID is added as an attribute on the end of the URL.  This causes the Ajax call to fail.

**Comment by toasty** [comment]
Thanks - but could you be more specific? Do you have an example URL I could use to reproduce this? (I don't have easy access to a clustered install)

**Comment by toasty** [comment]
Closing as old and unconfirmed.
