### ISSUE TITLE
Price in drop down isn't tier price

### ISSUE THREAD

**Issue by bajanga** [organicinternet/magento-configurable-simple#20]
Hi there,

Thanks for the great extension, saved us so much time and it's working well! We're just having one issue:

We're seeing the normal price in the drop down select, but seeing the tier price in the normal tier price areas. So in the drop down you'll see, for example, $49, but the price below is $22 (tier price) and if you change your selection, the $22 becomes $49... but the price after you add to cart is $22 (which is correct). These aren't custom options, and every simple product has a tier price. We've commented out the empty getTierPrice array so the page shows the tier price. We're using:

Magento 1.4.1.1
SCP 0.7.5
No JS errors
No other extensions on the page besides lightbox
No errors in the log

Can send you URL, but you have to be in a special group to see tier prices. Please PM me if you need those details, or if this is an issue that hasn't already been resolved.

Appreciate the help!

**Comment by toasty** [comment]
Hi Bajanga, 

Firstly thanks for the very clear bug report, if only they were all like that :)

I think by commenting out the empty getTierPrice function you're doing something SCP doesn't expect so I'm not too surprised it acts a little oddly.  Normally with SCP a tier price block for the matching associated product will load in once you've selected all configurable options - is this not happening for you?

**Comment by bajanga** [comment]
Hey Toasty,

Thanks for the quick response! I've tried putting the empty getTierPrice back in, which removes the tier price message/price, but the price on the drop down and price-span stay as normal prices. Till you add to cart, then you see the tier price.

Let me know if that makes sense or need to see a URL. I'd rather PM a URL if that's ok.

Thanks again.

**Comment by toasty** [comment]
Yeah it's probably easiest to mail or PM me a link and I'll take a look. (magentocommerce.com keeps giving me database errors at the moment, so maybe mail me at matt@organicinternet.co.uk ?)

**Comment by toasty** [comment]
closing as old
