### ISSUE TITLE
Full crash: Invalid Method...

### ISSUE THREAD

**Issue by Tellfjord** [organicinternet/magento-configurable-simple#21]
After install i get the following error when i try to edit a product. This Error is on backend: 

Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product::isUniversal(Array
(
)
)

Trace:
#0 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/design/adminhtml/default/default/template/catalog/product/tab/vaf.phtml(6): Varien_Object->__call('isUniversal', Array)
#1 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/design/adminhtml/default/default/template/catalog/product/tab/vaf.phtml(6): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product->isUniversal()
#2 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Block/Template.php(212): include('/home/httpd/vho...')
#3 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Block/Template.php(239): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#4 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Block/Template.php(253): Mage_Core_Block_Template->renderView()
#5 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#6 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Block/Abstract.php(753): Mage_Adminhtml_Block_Template->_toHtml()
#7 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/local/Elite/Vaf/Model/Observer.php(72): Mage_Core_Block_Abstract->toHtml()
#8 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/App.php(1228): Elite_Vaf_Model_Observer->doTabs(Object(Varien_Event_Observer))
#9 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/App.php(1209): Mage_Core_Model_App->_callObserverMethod(Object(Elite_Vaf_Model_Observer), 'doTabs', Object(Varien_Event_Observer))
#10 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/Mage.php(416): Mage_Core_Model_App->dispatchEvent('core_block_abst...', Array)
#11 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Block/Abstract.php(219): Mage::dispatchEvent('core_block_abst...', Array)
#12 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(430): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#13 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(446): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#14 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(238): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
#15 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(204): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#16 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(209): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#17 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(343): Mage_Core_Model_Layout->generateBlocks()
#18 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(270): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#19 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Adminhtml/Controller/Action.php(263): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
#20 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(240): Mage_Adminhtml_Controller_Action->loadLayout(Array)
#21 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/local/Elite/Vaf/controllers/Admin/Catalog/ProductController.php(26): Mage_Adminhtml_Catalog_ProductController->editAction()
#22 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Elite_Vaf_Admin_Catalog_ProductController->editAction()
#23 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#24 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(177): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#25 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/App.php(304): Mage_Core_Controller_Varien_Front->dispatch()
#26 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/Mage.php(596): Mage_Core_Model_App->run(Array)
#27 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/index.php(80): Mage::run('', 'store')
#28 {main}

This error is on the frontend: 

Invalid method OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product::isInEnabledCategory(Array
(
    [0] => Elite_Vaf_Model_Catalog_Category_FilterImpl Object
        (
            [config:protected] => 
        )

)
)

Trace:
#0 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/local/Elite/Vaf/Block/Product/View.php(40): Varien_Object->__call('isInEnabledCate...', Array)
#1 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/local/Elite/Vaf/Block/Product/View.php(40): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product->isInEnabledCategory(Object(Elite_Vaf_Model_Catalog_Category_FilterImpl))
#2 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/local/Elite/Vaf/Block/Product/View.php(26): Elite_Vaf_Block_Product_View->shouldApplyName(Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#3 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/local/Elite/Vaf/Block/Product/View.php(20): Elite_Vaf_Block_Product_View->applyName(Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#4 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Catalog/Block/Product/View.php(47): Elite_Vaf_Block_Product_View->getProduct()
#5 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Block/Abstract.php(218): Mage_Catalog_Block_Product_View->_prepareLayout()
#6 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(430): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#7 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(446): Mage_Core_Model_Layout->createBlock('catalog/product...', 'product.info')
#8 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(238): Mage_Core_Model_Layout->addBlock('catalog/product...', 'product.info')
#9 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(204): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#10 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/Layout.php(209): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#11 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(343): Mage_Core_Model_Layout->generateBlocks()
#12 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Catalog/controllers/ProductController.php(115): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#13 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Catalog/controllers/ProductController.php(149): Mage_Catalog_ProductController->_initProductLayout(Object(OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Product))
#14 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_ProductController->viewAction()
#15 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#16 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(177): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/code/core/Mage/Core/Model/App.php(304): Mage_Core_Controller_Varien_Front->dispatch()
#18 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/app/Mage.php(596): Mage_Core_Model_App->run(Array)
#19 /home/httpd/vhosts/auto-gruppen.se/httpdocs/magento/index.php(80): Mage::run('', 'store')
#20 {main}

Please help!

**Comment by toasty** [comment]
Hiya, 

I strongly suspect this is a module conflict rather than an SCP bug. 
There is no isUniversal() function in core Magento (at least 1.4) or SCP.

See this other issue that was raised a couple of months ago for more general info on this sort of thing: https://github.com/organicinternet/magento-configurable-simple/issues/closed#issue/12

Matt

**Comment by toasty** [comment]
Closing as no comment for a while and almost certainly a module conflict
