### ISSUE TITLE
Magento 1.5 compatibility?

### ISSUE THREAD

**Issue by erikstr** [organicinternet/magento-configurable-simple#22]
Thank you for the great extension! I found it recently and am now testing it on a Magento 1.501 installation. However I get this error when selecting an attribute:

Fatal error: Call to undefined method Mage_Catalog_Helper_Product::initProductLayout() in /app/code/core/Mage/Catalog/controllers/ProductController.php on line 67

Has anybody tested the extension on 1.5? Are there any known incompatibilities or am I doing something wrong?

Thank you in advance and best regards,
Erik

**Comment by toasty** [comment]
Have you seen http://www.magentocommerce.com/boards/viewthread/219845/ ?
The latest release of SCP works with Magento 1.5, but you may have to manually install it as Magento Connect seems to be behaving badly. (webpage says latest is 0.8.*, but then only offers 0.7.4 when you try to install via the key in your MCM)

Matt

**Comment by erikstr** [comment]
No, I didn't find that ... Thank you! I'll give it a try today.

Erik

**Comment by erikstr** [comment]
Hi again

I made a manual "install" - downloaded the archive and copied the files to their locations and now the extension works perfectly!

Thank you, Matt :)

**Comment by nerotic** [comment]
I had this same issue with 0.8.1.  I noticed that 0.8.0 was actually .2k bigger so I figured what the hell, I'd give it a shot and it worked like a charm.

**Comment by toasty** [comment]
_Ahem_ Yeah 0.8.1 was a botched package attempt. 0.8.2 and 0.8.0 are both fine (and the same) though. 

Presumably the problem still exists with MCM where when you paste the key that the Magento website gives you it still offers SCP v0.7.4?

**Comment by nerotic** [comment]
Indeed it does :)

**Comment by erikstr** [comment]
hi again :)

where could I get the 0.8.2 version from? on github there is only 8.1 and now I can't remember which version I really pulled in ...

Although I don't get any errors, this makes me nervous :)

**Comment by toasty** [comment]
As I said, 0.8.0 and 0.8.2 are the same. 0.8.1 and 0.8.2 were just attempts to get MCM to show a new version instead of 0.7.4, but it didn't work. (and yeah i screwed up the 0.8.1 build, but that's a separate issue!)

I've done a push so the releasedVersions folder will have been updated anyway

**Comment by erikstr** [comment]
OK, I see ... Thank you!
