### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bpaulin** [organicinternet/magento-configurable-simple#222]
Hi,

We want to use your module for one project.
Can you tell us what the license is?

**Comment by oviliz** [comment]
Hi Bruno,
thanks for your reply.

It looks like the last extension update was released by the last months of
2013. If that's true, I should be covered by the year upgrade, isn't?

Please let me know.
Thanks.
Cri

**Comment by oviliz** [comment]
Sorry! My huge mistake, I was thinking to reply to another email... :O
My apologies...

**Comment by kojiromike** [comment]
bump: What is the license for this extension?

**Comment by rubberduck203** [comment]
You may not be aware of this, but legally, without a license, no one can use your code. 

http://opensource.stackexchange.com/q/1720/775

**Comment by timetimetimetime** [comment]
Please add a license.

**Comment by almera-vs** [comment]
add a license or go to hell with this privatized repo
