### ISSUE TITLE
How do you guys import your configurable products??

### ISSUE THREAD

**Issue by erikstr** [organicinternet/magento-configurable-simple#23]
I was just wondering if SCP makes any mods to the DB or just switches some logic (sorry, I haven't looked into the code yet). Either way, what is the best or preferred method for mass importing of configurable products??

Erik

**Comment by toasty** [comment]
```
I was just wondering if SCP makes any mods to the DB
```

No, some select queries are changed, but no writes are, and there's no schema changes etc either.

```
Either way, what is the best or preferred method for mass importing of configurable products??
```

I wish I knew, seriously :)  I've had my head in the coding side of Magento but not so much the inventory management side...

**Comment by toasty** [comment]
...also the magento forum would be a better place for this sort of thing - it's not really an issue/bug with scp is it? :D

**Comment by erikstr** [comment]
well, I didn't say it's a bug in SCP :-) However, it is an _issue_  related to SCP :))

And after I read this thread:
http://www.magentocommerce.com/wiki/3_-_store_setup_and_management/import_export/how_to_automatically_import_simple_grouped_and_configurable_products?do=show

and also this one:
http://www.deepcodeonline.com/blog/magento/update-how-to-import-configurable-and-simple-products-in-magento-1-4-1-with-label-on-the-images-and-super-products-attribute-linking/

... I have the feeling that nobody has a clear idea of how a clean import really goes ... On the other hand I find this small SCP community here at Github in some way more profound than on the Magento forum. I might be wrong, but you all here know what you are talking about ...

Of course I could purchase the import extension available on MagentoConnect, but an import is a very crucial and basic function, which I would like to manage myself.

Erik

**Comment by erikstr** [comment]
OK, I decided to import simple products only and then assign them to configurables in the admin. 

Check the new import function in Magento 1.5 - it is REALLY FAST!!!

Erik

**Comment by ataripixel** [comment]
Guys, I know this topic isn't totally directly related to SCP, but I thought the value from the conversation was such that I should mention the method I'm using. I'm in no way affiliated whatsoever with this developer, but yesterday I discovered this solution. Read the reviews, email the guy, pay the $99 and you'll never look back. I hope it helps. I used it for the first time yesterday and combined with this plugin, configurable products are awesome.

http://www.magentocommerce.com/magento-connect/bolasevich/extension/1894/custom-bulk-product-import-+-export-with-tier-pricing--product-custom-options--configurable-products--bundle-products--grouped-products--downloadable#overview

**Comment by arielallon** [comment]
As @ataripixel noted, this isn't necessarily the right place for this, and I am also completely unaffiliated with this developer, but uRapidFlow (with the Pro add on) by unirgy is the best investment for a Magento store owner or developer I have ever used. 
http://www.unirgy.com/products/urapidflow/

It is faster than Magento's new import, provides comprehensive, useful errror reporting, and can handle pretty much anything you need to import for the catalog.

Highly recommended.

**Comment by mlxstore** [comment]
Use: http://www.mlx-store.com/magento-extensions/import-export/export-import-bulk-product-with-configurable-product-bundle-product-grouped-product-downloadable-product-tier-price-group-price-related-products-up-sells-cross-sells-product-tags-magento.html
