### ISSUE TITLE
Image update not resizing

### ISSUE THREAD

**Issue by bb80** [organicinternet/magento-configurable-simple#24]
It works fine when:
Dynamically update displayed product picture?  = YES
Update gallery images as well as main image? = YES

But not when: 
Dynamically update displayed product picture?  = YES
Update gallery images as well as main image? = NO

The updated displayed product image does not resize and gets cropped in product preview window box.

Please help...

**Comment by bb80** [comment]
Also, the gallery image is added for every drop down attribute. ie. i choose small size - image is added to gallery, i then choose strawberry flavour - same image added again to gallery.

Please help...

**Comment by toasty** [comment]
Are you're using a lightbox extension or similar? If so then that'll be the cause.
If not it's likely that your html is different from what scp is expecting. Send me an email or PM on the magento site with a link to where it's happening and I'll take a look for you when I get a few mins free.

**Comment by lapongua** [comment]
I have the same issue. I use a lightbox extension and when updated displayed product image does not resize and gets cropped in product preview window box.

Dynamically update displayed product picture? = YES
Update gallery images as well as main image? = NO

Have you solved?

thanks.

**Comment by grosykevin** [comment]
Hello Toasty, would it be possible to have your e-mail address?
