### ISSUE TITLE
Attribute titles and options labels for multiple stores

### ISSUE THREAD

**Issue by anneholst** [organicinternet/magento-configurable-simple#25]
Thank you for SCP! The extension has solved a huge problem for me!  

After installing I have experienced one puzzling and annoying problem, however:  

My webshop is set up to work in three different countries (Denmark, Norway and Sweden). I.e., the Magento installation includes three stores, each using a different language, and each with its own country specific domain name. The same products are to be sold in all three countries.  

When I add a new product attribute to match the product, Magento automatically asks me to fill in both a title (e.g. Material) and all options labels (e.g. rust, galvanised) for each of the stores plus for admin purposes. I have filled in he titles and labels for each store in the appropriate language, and the admin titles and labels in English:  
http://rapidshare.com/files/448381123/Picture_10.png 

As intended, on front-end, the Danish store shows options labels in Danish, the Swedish store shows options labels in Swedish, etc. But the titles above the options drop-downs are shown in all three stores in English:  
http://www.landhave.dk/klassiske-hojbede/kvadratisk-hoejbed.html  

I am quite puzzled why the options labels show correctly, but not the titles.  

Is here anything I can do to correct the problem, or will I have to create separate attributes and attribute sets for each store?  

Hope you can help me!  

Please write me back on email for user name and password if necessary.

/Anne

**Comment by toasty** [comment]
I've had a quick look and though I've not yet spotted what is it about SCP that's doing this, you can fix it temporarily by editing core Magento code here:
app/code/core/Mage/Catalog/Model/Product/Type/Configurable/Attribute.php

Change line 72 from:
        } else if (!is_null($this->getData('label')) && $this->getProductAttribute()) {
to
        } else if ($this->getProductAttribute()) {

I'll leave it as an open bug as something I need to look into so that you don't need to edit core code to fix it

Matt

**Comment by anneholst** [comment]
Thank you so much, Matt!

Saved me a lot of trouble once again!
