### ISSUE TITLE
Not able to see custom options in admin panel order detail page

### ISSUE THREAD

**Issue by suy99** [organicinternet/magento-configurable-simple#259]
Hi,
My Configurable product is working great,
But, I have custom options set to simple products and those simple products are associated to configurable product.

My problem is the custom options are not getting passed into the cart and so in the admin panel order detail page.

Please help as this is urgent issue.

Thanks

**Comment by kidcajes** [comment]
If your configurable product is working then the size of your associated simple product will be appended. Custom options only appears on simple product alone. In short you cannot display custom options if your using the simple product as associated simple product to the configurable product. 

Example Backend: 
  Configurable: Blue Tshrt
     Associated SP: 
                 Blue Tshrt S (no custom option)
                 Blue Tshrt M (no custom option)

Frontend view:
Blue Tshirt with options S & M

If the associated simple product has custom option, they definitely not appear.

**Comment by suy99** [comment]
Hi @kidcajes thanks for the reply, I don't want to show them on frontend, but i want to get the custom options value in the order item level.

I have ajax cart, that's causing the issue, because when i add the product to cart from product view page then i am able to see the customs options in cart and admin panel order page as well.

But when i add the product to cart from catelog page through ajax cart then i am NOT able to see them in cart and admin panel order page as well.

**Comment by kidcajes** [comment]
Ahh ok. Check your ajax code. I think it needs to pull the custom-option of from the OrganicInternet SimpleProduct not from the Core. Because OrganicInternet SP already override the simple product core options.

**Comment by suy99** [comment]
@kidcajes I have checked the code but not seems to be working, by the way may i know how can i override the ajax cart custom option code with organicInternet custom option code, i have tried adding the scpwrapper and  scpoptions but didn't work.

**Comment by kidcajes** [comment]
Are you using an extension for this? What extension would that be? If not, you have to ask some developer to do that if you're not a developer yourself. Anyway, logically the ajax cart code is pulling the default/core simple product custom option. Check the blocks in OrganicISP.
