### ISSUE TITLE
Options prices show 0.00

### ISSUE THREAD

**Issue by snowdog** [organicinternet/magento-configurable-simple#3]
"Price from" shows correct price but after choosing an option price changes to 0.00

**Comment by snowdog** [comment]
Sorry, please forget this ticket. My problem was caused by Layered Navigation Indices Cache

**Comment by toasty** [comment]
ok

**Comment by nsvreddy** [comment]
After installation of SCP,if i select custom option it is not update the price in product view page for simple products..
plese give me a solution
