### ISSUE TITLE
Homepage loading within product configuration page

### ISSUE THREAD

**Issue by gcole54** [organicinternet/magento-configurable-simple#33]
Hello,

I was wondering if you could help me please? I have recently installed your extension simple configurable products which is fantastic, yet I'm having some troubles on the front end product configuration page.

When an option is selected from the drop down list, my homepage loads inside the current page just below the 'Product Quantity' section of the site and the 'Price & add to cart' section.

please feel free to visit here: http://www.musedesignguide.co.uk/shop/170gsm-full-colour-gloss-flyers

I am using Magento ver. 1.4.2.0, SCP 0.7.4 

The problem DOES go away when SCP is uninstalled
To my knowledge there are not any javascript errors.

I'm using the intro theme from yootheme's and have MageBridge installed - http://www.yireo.com/software/magebridge

Have tried editing all files I'm able to, yet not hugely experienced with javascript or magento. Would appreciate any help anyone could give me.

Thanks again,

Paul

**Comment by kwilcox85** [comment]
I am having the same exact issue also.  If you find a fix please let me know.  This is kind of frustrating.

**Comment by kwilcox85** [comment]
Could this issue be because of prior third party extensions installed?

**Comment by toasty** [comment]
This commit https://github.com/organicinternet/magento-configurable-simple/commit/00ed44478c290d9856649d119a0ba6bd529793c9 fixes this issue. If you can't upgrade your version of SCP to the latest, you can apply these changes manually
