### ISSUE TITLE
Fatal error: Call to undefined...

### ISSUE THREAD

**Issue by annama1** [organicinternet/magento-configurable-simple#34]
Hi,

 I have installed this module (version 1.5) into my Magento project (version 1.5.0.1). And when I try to change the select option in product detail page, I get this error: "Fatal error: Call to undefined method Mage_Catalog_Helper_Product::initProductLayout() in C:\xampp\htdocs\magento_base\app\code\core\Mage\Catalog\controllers\ProductController.php on line 67". The new price is correctly displayed and all the product features but under the select field that error is displayed.

Thanks

**Comment by toasty** [comment]
You need to use a new version of SCP for Magento 1.5 compatibility. SCP doesn't have a 1.5 version so I'm a bit confused about that but you should ideally be using 0.8.2 which is the latest version to date. See: https://github.com/organicinternet/magento-configurable-simple/tree/master/releasedVersions

**Comment by annama1** [comment]
Sorry, I have forgotten it. I have installed SCP Version 0.8.2. and Magento (version 1.5.0.1). When I change the option I get the error.
I have also tested SCP Version 0.8.2 and Magento (version 1.5.1) and the same error is displayed.

Thanks,

**Comment by toasty** [comment]
app/code/community/OrganicInternet/SimpleConfigurableProducts/controllers/AjaxController.php

Check which version of this file you have against the one shown here in github. It sounds like you might have an old version somehow. SCP 0.8 does not call initProductLayout any more so you should never see this error.

**Comment by annama1** [comment]
Ok, This is what happened. I installed SCP extension from http://www.magentocommerce.com/magento-connect/Matt+Dean/extension/596/simple-configurable-products (Magento Connect Version: 2.0). And this install in my project 0.7.4 (stable). I also tried with tab releases and the same version was installed. So this was the problem the Magento Connect version is not your last release. But now we have the correct release, here is another problem. 
Look at this example: http://www.tucolchononline.com/colchon-visco-junior.html. There are different options with different prices ("Medidas"). Try to add to the cart (button "Añadir") one option more expensive than the initial price. As you can see on the cart on the left side, the added product is the option that we choosed but the price is the started price, not the choosed product price.

Thanks

**Comment by toasty** [comment]
Hola - En esa pagina hay un error de javascript:

```
document.getElementById("old-price-109") is null
http://www.tucolchononline.com/colchon-visco-junior.html
Line 295
```

El error está en el función reload_offers() que no es una parte de SCP, pero creo que es por eso que el javascript de SCP no funciona.
(Si utilizas 'firebug' o algo parecido es muy fácil ver y localizar los errores de javascript)

I hope you understood my Spanish. I'm still not very good at it! :)

**Comment by annama1** [comment]
Thank you, I solved the javascript error and it seems all it is working fine.
