### ISSUE TITLE
v1.4 change to Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Grid

### ISSUE THREAD

**Issue by benz** [organicinternet/magento-configurable-simple#4]
OrganicInternet_SimpleConfigurableProducts_Adminhtml_Block_Catalog_Product_Edit_Tab_Super_Config_Grid copies the _prepareCollection() method of the Mage block in the title.

However in version 1.4.0.1 the mage block has changed slightly to include a check for ReadOnly in the grid:
        if ($this->isReadonly()) {
            $collection->addFieldToFilter('entity_id', array('in' => $this->_getSelectedProducts()));
        }

**Comment by toasty** [comment]
Well spotted, cheers.
(I've added it but I'm still testing so not uploaded anything yet.)
