### ISSUE TITLE
Simple product max sale qty

### ISSUE THREAD

**Issue by olivermontes** [organicinternet/magento-configurable-simple#40]
this is my configuracion
- create a simple producto ( product name 1M ) and ( product name 25M ) in same configurable product
- product 1M have option "max sale qty = 24" 
- in product view try buy "product 1M = 25 or more" and show menssage "the maximum quantity allowed for purchase is 24" but this menssage show in mageno 404 page in siple product URL (don't back to configurable product)

any sugestion?

thx.

**Comment by toasty** [comment]
There are some bugs with SCP and Magento 1.5 with handling errors that happen in the cart not redirecting back to the right place. I've put a fix together but I'm not sure it's perfect yet. I've just pushed it so it's here: 
https://github.com/organicinternet/magento-configurable-simple/commit/c137e4bf979fcc645466352a6ead41058538267b  

Can you let me know if you update these 2 files whether it fixes your problem or not please?
(If not, give me more detail of your magento versions etc, and/or mail me a link to where it's happening)

**Comment by olivermontes** [comment]
yes, this fixed nice work!! thx very much :D

**Comment by ghost** [comment]
Please refer to my comment on the commit for a needed fix.

**Comment by lapongua** [comment]
Thanks works perfect on Magento 1.7.0.2
