### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ghost** [organicinternet/magento-configurable-simple#5]
updateSpecialPriceDiplay

Diplay?

**Comment by toasty** [comment]
hah, well spotted. Thanks to the wonders of cut and paste it's typo'd everywhere it needs to be though, so doesn't look like it's causing a problem. I'll update this when I next make some changes to SCP.

**Comment by ghost** [comment]
yah, i saw that too, totally know what you mean though, thanks for making the extension, a+

**Comment by toasty** [comment]
It's fixed now.
I've not put it up on Magento Connect yet, but will shortly.
