### ISSUE TITLE
404 in admin panel

### ISSUE THREAD

**Issue by nbrewer** [organicinternet/magento-configurable-simple#55]
I've read previous posts and recommendations on fixing this issue, but it's just not working.

Cache cleared (cache was disabled anyway, but still attempted to enable/flush it)
Re-Indexed all data.
Restarted apache
installed manually and with the MCM (always using backed up file system)
Permissions set.

magento 1.5.1 attempting to install SCP 8.0, 8.2MCMv1, or 8.2MCMv2 all result in same behavior 404 on error page.

This would be fine if the configuration data were easily locatable in the database, but I've been unable to locate a table either.

**Comment by toasty** [comment]
It's some quirk of the way the magento admin config works as far as I know.   I've never heard of anyone still having a problem after just logging out of admin and then back in?

**Comment by nbrewer** [comment]
Wow, I really feel silly. We use very persistent cookies on our servers, clearing out my cookies and thus my session to the admin panel resolved it. Thanks for the prompt reply.
