### ISSUE TITLE
Custom Option changes price to $0.00 (CE 1.6.2)

### ISSUE THREAD

**Issue by z2x2** [organicinternet/magento-configurable-simple#95]
I've looked through the issues posted by other people, but they're all related to having an old version of SCP? I just installed the latest from the github on CE 1.6.2, first time I have ever installed SCP. No issues with install, but did have to go in and remove the "group_price" parts of the indexer updated for CE 1.7.

Everything else works fine, it's just that after selecting all of the configurable options and then selecting any custom option will set disaplyed price to $0.00. (Price is still accurate [Not $0.00] in cart.)

Edit: Have two instances of the price on the product view page, one without _clone and one with. Also took a look at the JS variables and would have to conclude it's a JS error as the price variable is NaN after selecting a custom option. Any idea how to go about fixing this?

EDIT2: SOLVED! See below.

**Comment by z2x2** [comment]
So I feel like a jackass now. Turns out it was my modified Options.php core file. Issue was not caused by SCP at all and it's now fixed!

**Comment by surflibre** [comment]
Hi,
I've got the same pb with a magento 1.7, and I can't solve it.
Where's the file Options.php magento/app/code/core/Mage/Catalog/Block/Product/View ?
thanks,

**Comment by z2x2** [comment]
surflibre - Yes, that is the right location of Options.php, but the only issue would with it was that I had modified it a few days prior to installing SCP in an attempt to get similar functionality. I just replaced it with the original Options.php that I had backed up to get SCP working. If you haven't modified any core files, then your problem most likely has a different solution.

If you wanted to try removing to the group_price like I did, which shouldn't be causing any issues in 1.7 (It only prevented me from reindexing the price index on 1.6.2), all you have to do is delete the highlighted sections from here: https://github.com/magdev/magento-configurable-simple/commit/6d88e5e1846713f579f79905dc3ed35112772ebc
